# Copyright 2019 The Protocol Buffers Language Server Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

service:
  golangci-lint-version: 1.17.x
run:
  deadline: 5m

  skip-dirs:
    - vendor$

  skip-files:
    - ".*\\.pb\\.go"
    - ".*\\.mock\\.go"
    - ".*(.|_)gen\\.go"

linters:
  enable-all: true
  disable:
    - depguard
    - dupl
    - gochecknoglobals
    - gochecknoinits
    - goconst
    - gocyclo
    - gosec
    - nakedret
    - prealloc
    - scopelint
  fast: false

linters-settings:
  errcheck:
    check-type-assertions: false
    check-blank: true
    exclude: .errcheckignore
  govet:
    check-shadowing: false
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  goimports:
    local-prefixes: github.com/micnncim/protocol-buffers-language-server
  maligned:
    suggest-new: true
  misspell:
    locale: US
  lll:
    line-length: 160
    tab-width: 1
  unused:
    check-exported: false
  unparam:
    algo: cha
    check-exported: false
  gocritic:
    enabled-checks:
      - rangeValCopy
    disabled-checks:
      - regexpMust
    enabled-tags:
      - performance
    settings:
      captLocal:
        paramsOnly: true
      hugeParam:
        sizeThreshold: 80
      rangeExprCopy:
        sizeThreshold: 512
      rangeValCopy:
        sizeThreshold: 128
issues:
  exclude-rules:
    - path: _test\.go$
      linters:
        - errcheck
        - maligned
