# Copyright 2019 The Protocol Buffers Language Server Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

runner:
  golint:
    cmd: golint $(go list ./... | grep -v /vendor/)
    format: golint
  govet:
    cmd: go vet $(go list ./... | grep -v /vendor/)
    format: govet
  unused:
    cmd: unused $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c: %m"
  errcheck:
    cmd: errcheck -asserts -ignoretests -blank $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c:%m"
  gosimple:
    cmd: gosimple $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c: %m"
  staticcheck:
    cmd: staticcheck $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c: %m"
  misspell:
    cmd: misspell $(git ls-files)
    errorformat:
      - "%f:%l:%c: %m"
  unparam:
    cmd: unparam $(go list ./... | grep -v /vendor/)
    errorformat:
      - "%f:%l:%c: %m"
  revive:
    cmd: revive -config=.revive.toml $(go list ./... | grep -v /vendor/)
    format: golint
  golangci:
    cmd: golangci-lint run --out-format=line-number ./...
    errorformat:
      - '%E%f:%l:%c: %m'
      - '%E%f:%l: %m'
      - '%C%.%#'
