name: Test
on: [push]
jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go modules directory
        uses: actions/checkout@v2

      - name: Cache Bazel binary from Bazelisk
        uses: actions/cache@v1
        with:
          path: ~/.cache/bazelisk/bin
          key: ${{ runner.os }}-${{ hashFiles('.bazelversion') }}

      - name: Test
        run: make test

